// src/components/Profile.jsx
import styled from '@emotion/styled'
import React from 'react'
import SvgMe from '../images/conor.svg'

export const Profile = () => {
    return (
        <Conor />
    )
}

const Conor = styled(SvgMe)`
    border-radius: 100px;
    width: 100px;
    height: 100px;
    margin-bottom: 20px;
    border: 3px solid ${({ theme }) => theme.palette.gold};   
`

// src/components/Profile.svelte
<div>
  <img src="/images/conor.svg" alt="Conor in real life" />
</div>

<style>
  div {
    text-align: center;
  }
  img {
    border-radius: 50%;
    width: var(--spacing-15);
    height: var(--spacing-15);
    border: 2px solid var(--gold);
    cursor: pointer;
    transition: all 0.4s ease;
  }
  img:hover {
    transform: scale(1.1);
  }
</style>
